# YAML配置 - 多媒体部分示例 (推荐方案)
# 每次修改完配置后，必须重启程序才能生效
# 使用 # 来注释掉某行

# 版本号
Version: "1.0.0"

# 日志级别(如果发生问题搞不定的，把info改成debug然后重启，再把出问题时候的日志发上来, 问题修复后再改回info)
LogLevel: info

# 第一个媒体部分 - Emby (保持原有配置不变)
Media:
  Executor: media.emby.Emby
  # Emby 特定配置 - 保持原有格式
  Server: http://your-emby-server:8096
  ApiKey: your-api-key
  # ... 其他 Emby 参数

# 第二个媒体部分 - FileCatcher (新增)
Media2:
  Executor: media.filecatcher.FileCatcher
  # FileCatcher 特定配置可以在这里添加
  # 例如：端口配置等

# 可以继续添加更多媒体部分
# Media3:
#   Executor: media.other_executor.OtherExecutor
#   配置参数...

# 播放器配置
Player:
  # 引用的播放机执行器(默认oppo)
  # 可供选择的执行器请看程序所在目录的player文件夹下，使用player.<filename>.<classname>来命名
  # 目前有以下几种:
    # player.oppo.Oppo
    # player.pioneer.Pioneer
  Executor: player.oppo.Oppo
  # 播放机ip, 改成你自己的
  IP: 192.168.1.11
  # SMB认证信息(按照下方格式，配置至少2个不同的用户, 不用smb可以不改), pioneer 不需要(由于固件限制只能在播放机上先手动进入共享目录, nfs同理)
  Auth:
    - Username: username1
      Password: password1
    - Username: username2
      Password: password2
  # udp超时时间，不要改
  UdpTimeout: 10
  # 是否优先启用nfs, true为使用nfs, false为使用smb
  NFSPrefer: true

  # 检测到开机后发送的控制按键，只支持pionner,  支持的按键有：ok, left, right, up, down, return, home
  # 默认的按键是在要进入的共享盘和子目录都在第一个的情况，其他情况请自行修改,按键之间会自动插入1秒的延迟。
  # 如果插入多1 秒的延迟可以像下面一样发送一个空的 key.(这里在 ok键后面插入空key增加 1 秒延迟是因为电影界面进入稍慢)
  StartupKeySequence:
    - right
    - ok
    -
    - ok
    - down
    - ok
  # 开机发送按键的延迟时间， 开机后发现smb,nfs需要一定时间，等待一会儿防止进目录后smb/nfs还没有出现。
  # 根据自己网络发现速度调整。
  StartupWait: 5
  # 指定强制挂载目录(一般可以留空或填null, 如果是飞牛等设备，必须填写nfs根目录，例如 fs/1000/nfs)
  ForceMountPath: null
  # 文件夹映射路径(不用的协议路径值可以留空)
  # 文件最后有路径配置说明, pioneer请参照 pioneer部分
  MappingPath:
    - Media: /path1 # Watcher监控的目录，确保与Watcher中配置的目标路径一致
      SMB: /smb_host1
      NFS: /192.168.1.10/path1
    - Media: /path2 # Watcher监控的目录，确保与Watcher中配置的目标路径一致
      SMB: /smb_host2
      NFS: /192.168.1.10/path2

# 电视配置
TV:
  # 引用的TV执行器(默认null不启用)
  # 可供选择的执行器请看程序所在目录的tv文件夹下，使用tv.<filename>.<classname>来命名
  # 目前有以下几种:
    # tv.sony_bravia.SonyBravia
    # tv.lg_webos.LGWebos
    # tv.oppo_hdmi.OppoHdmi
    # tv.hdfury.Hdfury
  Executor: null
  # 电视或其它设备的IP, 改成你自己的
  IP: 192.168.1.12
  # 电视控制识别码, 改成你自己的
  Key: "1234"
  # 播放机对应的HDMI口, 改成你自己的
  HDMI: 0
  # 播放结束后电视默认切换策略, 改成你自己的
  # null 执行默认策略, sony为跳转到emby app, Lg为返回原来页面
  # app=xxxx 例如"app=netflix" 代表返回netflix app
  # hdmi=x 例如"hdmi=3"代表返回 hdmi 3输入源
  # oppo系列，如果希望结束后停留在HDMI输入 则填写hdmi=1；如果选择HDMI输入直通 则填写pass=1。
  PlayStopUri: null

# AV功放配置
AV:
  # 引用的AV执行器(默认null不启用)
  # 可供选择的执行器请看程序所在目录的av文件夹下，使用av.<filename>.<classname>来命名
  # 目前有以下几种:
    # av.onkyo.Onkyo 所有可用命令可查看docs/onkyo-eiscp-command.yaml
    # av.yamaha.Yamaha 目前可用命令如hdmi=hdmi1(或hdmi2、hdmi3、av1等等）
  Executor: null
  # AV功放ip, 改成你自己的
  IP: 192.168.1.13
  # 播放开始时功放切换策略，改成你自己的,默认代表切换副输出以及切到bd
  PlayStartUri: hdmi-output-selector=out-sub&source=bd
  # 播放结束后功放切换策略，改成你自己的(默认代表切回主输出且切到tv-earc)
  PlayStopUri: hdmi-output-selector=out&source=tv 