# YAML配置
# 每次修改完配置后，必须重启程序才能生效

# 版本号
Version: "1.0.0"

# 日志级别(如果发生问题搞不定的，把info改成debug然后重启，再把出问题时候的日志发上来, 问题修复后再改回info)
LogLevel: info


# 媒体库配置
Media:
  # 引用的媒体库执行器, 不要改
  Executor: media.emby.Emby
  # 设备客户端, 不要改
  Client: Emby Bluray Poster
  # 媒体库服务端显示的设备名称， 不要改
  Device: Bluray Poster
  # 设备唯一id， 不要改
  DeviceId: whitebrise
  # 媒体库服务器地址:端口, 改成你自己的
  Host: http://192.168.1.10:8096
  # 媒体库服务器的用户名, 改成你自己的
  Username: aabbccddee
  # 媒体库服务器的密码, 改成你自己的
  Password: abcd123456789
  # 阻止播放的设备列表, 改成你自己的, 一行一个
  # 在app上选片后，本身设备也会进行串流播放，通过添加设备名称列表，比如你想选片的电视/手机，可以阻止它们串流播放，避免播放器和app两个同时播放
  # 该设备名称可在 emby服务器-设备 里看到，每个设备图片下面第一排就是设备名
  # 也可以emby里不点击播放按钮而是点击收藏/已播放按钮也可以启动影片。这样就可以不填BlockDevices，加载速度会比点击播放按钮然后阻止选片设备播放快一点
  BlockDevices:
    - SONY XR-77A95L
  # 排除的文件扩展名, 一行一个
  # 格式命中的文件会直接用点击海报的那个设备播放，不会调用蓝光机
  ExcludeVideoExt:
    - mp4
    - mkv
  # 重复检测时间, 不要改
  RepeatFilterTimeout: 120


# 播放器配置
Player:
  # 引用的播放机执行器，支持oppo和pioneer, pioneer只支持高清先生固件(m9708测试通过)
  # oppo填写player.oppo.Oppo，pionner请改成player.pioneer.Pioneer
  Executor: player.oppo.Oppo
  # 播放机ip, 改成你自己的
  IP: 192.168.1.11
  # SMB认证信息(按照下方格式，配置至少2个不同的用户, 不用smb可以不改), pioneer 不需要(由于固件限制只能在播放机上先手动进入共享目录, nfs同理)
  Auth:
    - Username: username1
      Password: password1
    - Username: username2
      Password: password2
  # udp超时时间，不要改
  UdpTimeout: 10
  # 是否优先启用nfs, true为使用nfs, false为使用smb
  NFSPrefer: true

  # 检测到开机后发送的控制按键，只支持pionner,  支持的按键有：ok, left, right, up, down, return, home
  # 默认的按键是在要进入的共享盘和子目录都在第一个的情况，其他情况请自行修改,按键之间会自动插入1秒的延迟。
  # 如果插入多1 秒的延迟可以像下面一样发送一个空的 key.(这里在 ok键后面插入空key增加 1 秒延迟是因为电影界面进入稍慢)
  StartupKeySequence:
    - right
    - ok
    -
    - ok
    - down
    - ok
  # 开机发送按键的延迟时间， 开机后发现smb,nfs需要一定时间，等待一会儿防止进目录后smb/nfs还没有出现。
  # 根据自己网络发现速度调整。
  StartupWait: 5

  # 文件夹映射路径(不用的协议路径值可以留空)
  # 文件最后有路径配置说明, pioneer请参照 pioneer部分
  MappingPath:
    - Media: /path1
      SMB: /smb_host1
      NFS: /192.168.1.10/path1
    - Media: /path2
      SMB: /smb_host2
      NFS: /192.168.1.10/path2


# 电视配置
TV:
  # 引用的TV执行器
  # 目前电视有2个，一个sony bravia，一个lg的, 根据你的电视类型选择，其它设备有2个，一个HDFURY,一个OPPO
  # 索尼就用tv.sony_bravia.SonyBravia, LG就用tv.lg_webos.LGWebos, HDFURY就用tv.hdfury.Hdfury,OPPO就用tv.oppo_hdmi.OppoHdmi
  Executor: tv.sony_bravia.SonyBravia
  # 电视或其它设备的IP, 改成你自己的
  IP: 192.168.1.12
  # 电视控制识别码, 改成你自己的
  Key: "1234"
  # 播放机对应的HDMI口, 改成你自己的
  HDMI: 0
  # 播放结束后电视默认切换策略, 改成你自己的
  # null 执行默认策略, sony为跳转到emby app, Lg为返回原来页面
  # app=xxxx 例如"app=netflix" 代表返回netflix app
  # hdmi=x 例如"hdmi=3"代表返回 hdmi 3输入源
  # oppo系列，如果希望结束后停留在HDMI输入 则填写hdmi=1；如果选择HDMI输入直通 则填写pass=1。
  PlayStopUri: null


# AV功放配置
AV:
  # 引用的AV执行器
  Executor: av.onkyo.Onkyo
  # AV功放ip, 改成你自己的
  IP: 192.168.1.13
  # 播放开始时功放切换策略，改成你自己的,默认代表切换副输出以及切到bd
  PlayStartUri: hdmi-output-selector=out-sub&source=bd
  # 播放结束后功放切换策略，改成你自己的(默认代表切回主输出且切到tv-earc)
  PlayStopUri: hdmi-output-selector=out&source=tv


#### 路径配置说明 -> 开始
#
#
#  路径配置的分割符全部都要改为"/", 无论你是windows还是linux还是其他的，无论原来的分割符是"/","//","\","\\"甚至"\\\\"，都统一改为"/"
#  路径以/开头, 结尾不要/
#  如果你的媒体路径是windows的路径，比如是"d:/video/"这种不以"/"开头的，需要填写emby媒体库设置中 `（可选）共享的网络文件夹 `，详情看readme.md。
#  不是smb和nfs都必须配置, 你用的哪个就配置哪个，另一个配置可以直接留空, 当然你全配置也没问题
#
#  有2种配置方式
#
#  比如我的文件夹分类是这样
#
#  NAS466C/Video/
#  ├── 电影/
#  │   ├── 电影1
#  │   └── 电影2
#  ├── 电视剧/
#  │   ├── 电视剧1
#  │   ├── 电视剧2/
#  │   │   ├── 电视剧2-s01
#  │   │   └── 电视剧2-s02
#  ├── 动漫/
#      ├── 动漫1
#      └── 动漫2
#
#  1. 傻瓜配置(注意路径中的大小写)
#
#  a. 首先获取emby媒体库里的地址(直接在媒体库里复制出来, 比如是/mnt/Video/电影),修改分隔符, 填写到 Media中(例如"/mnt/Video/电影")
#  b. 打开oppo, 点击网络, 显示出来的smb设备和nfs设备就是路径开头,例如能看到一个smb设备"NAS466C", 一个nfs设备"192.168.1.10"
#  c. 继续点击，直到找到你媒体库挂载的相同路径文件夹, 比如我点击的顺序是NAS466C -> Video -> 电影
#    (注意中间还有一个图片/音乐/视频, 那个是oppo自己虚拟的，跟你的实际目录没关系，忽略掉)
#  d. 那么我的SMB路径就是 "/NAS466C/Video/电影", nfs同理
#  e. 自己的媒体库有几个路径就配几个，确保每个媒体库路径都有正确的配置, 比如/NAS466C/Video/电视剧，/NAS466C/Video/动漫
#
#  2. 进阶配置(如果你上面配置的路径中包含中文, 强烈建议往下看)
#
#  傻瓜配置后,你有以下3个目录
#  media："/mnt/Video/电影"
#  "SMB": "/NAS466C/Video/电影"
#  "NFS": "/192.168.1.10/Video/电影"
#
#  media："/mnt/Video/电视剧"
#  "SMB": "/NAS466C/Video/电视剧"
#  "NFS": "/192.168.1.10/Video/电视剧"
#
#  media："/mnt/Video/动漫"
#  "SMB": "/NAS466C/Video/动漫"
#  "NFS": "/192.168.1.10/Video/动漫"
#
#  看第一个目录, 可以发现后面路径都是/Video/电影, 相同的路径是可以约掉的
#  例如我可以约掉 "电视剧" 修改成
#  media："/mnt/Video"
#  "SMB": "/NAS466C/Video"
#  "NFS": "/192.168.1.10/Video"
#  甚至也可以继续约掉 "Video" 修改成
#  media："/mnt"
#  "SMB": "/NAS466C"
#  "NFS": "/192.168.1.10"
#
#  所以，配置的最佳路径为
#  media："/mnt"
#  "SMB": "/NAS466C"
#  "NFS": "/192.168.1.10"
#
#  如果第一步傻瓜配置中路径有中文的，建议按第二步说的，把相同的路径约掉，尽量避开中文。
#
#### 路径配置说明 -> pioneer
# 不管 smb,或者 nfs, 只支持单一共享文件夹, 如果有多个共享文件夹, 建议合并成一个上层目录再通过 nfs 或者 smb 进行共享.
# 否则播放不同目录的电影都需要手动在播放机上切换到对应目录, 比较麻烦, 还可能切换的目录对不上就播放失败,导致黑屏, 只能重启播放机.
# 以 nfs 举例: media部分和上面 oppo一致,
# nfs部分去掉 ip后面以"-"开头那一节, 比如
# Media: /volume1/Media/Movie
# NFS: /10.0.1.4/Movie
# 在播放机看到的路径是 10.0.1.4/-volume1-Media/Movie, 去掉"-volume1-Media"就是/10.0.1.4/Movie
#
# 多个硬盘或多个分区如何用一个共享目录(可以有子目录, 但是最层用于共享的目录只能一个):
# 1. 比较笨的办法就是把蓝光片全部落到一个硬盘然后共享.
# 2. 多个硬盘组 raid, 把蓝光放到一个目录,然后共享.
# 3. 不用动数据,但是需要折腾(需要执行 linux命令)的方法, 以群辉nfs举例:
#   1) 新建一个共享文件夹什么都不放, 我的是在/volume4/BluRay.
#   2) 将之前的共享文件夹的 nfs关掉(目的是不让蓝光机看到, 防止挂载错目录).
#   3) 将每个其他盘的电影目录挂载到 /volume4/BluRay 目录下.
#      打开 DSM -> 控制面板 -> 计划任务 -> 新增 -> 触发的任务 -> 用户自定义脚本,
#      任务名称自定, 用户账号选 root, 事件选开机, 已开启勾选上,
#      点击任务设置标签,用户自定义脚本填写:
#      #!/bin/bash
#      mount --bind /volume1/Media/Movie/ /volume4/BluRay/Media
#      mount --bind /volume2/Share/Movie/ /volume4/BluRay/Share
#      保存, 保存后点击运行看是否成功, 正常应该在/volume4/BluRay/Media 目录看到 /volume1/Media/Movie/ 目录下的内容
#   mount 的目标目录可以随便指定(最好不要有特殊字符), 只要在 NFS填对应的就行
  # 配置好后，先启动播放机，点击电影，点击共享的目录比如我是 10.0.1.4,
  # 然后点击共享的目录， 我这里是 -volume4-BluRay (一定要先点到这里,不然点播放会黑屏只能重启)， 然后就可以正常使用 emby播放
#
#### 路径配置说明 -> 结束
